MiSiM/Controllers/FoodController.cs
using MiSiM.Models;
using System.Linq;
using System.Web.Mvc;

namespace MiSiM.Controllers
{
    public class FoodController : Controller
    {
        // GET: Food
        public ActionResult Index()
        {
            return View();
        }

        //conte

        public ActionResult Menu()
        {
            ViewBag.Message = "Menu";

            return View(Food.FakeList);
        }

        // GET: Food/Details/5
        public ActionResult Details(int id)
        {
            Food a = (from Food food in Food.FakeList where food.Id == id select food).FirstOrDefault();
            return View(a);
        }

        // GET: Food/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Food/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Food/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Food/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Food/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Food/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

MiSiM/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="cs">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="//fonts.googleapis.com/css?family=Raleway:400,300,600" rel="stylesheet" type="text/css">
    <link href="//fonts.googleapis.com/css?family=Open+Sans:300,400,600" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="~/Content/normalize.css">
    <link rel="stylesheet" href="~/Content/skeleton.css">
    <link rel="stylesheet" href="~/Content/main.css">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="icon" type="image/png" href="images/favicon.png" />
</head>
<body>
    <!-- Primary Page Layout
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <div class="nav">
        <div class="navBg">
            <img src="~/images/Logo2.svg" id="logo" class="u-pull-left">
            <img id="menuIco" class="u-pull-right" src="~/images/iconfinder-icon.svg" onclick="meny()">
            <ul id="nav1">
                <li><a href="@Url.Action("Index","Home")">Domu</a></li>
                <li><a href="@Url.Action("Menu", "Food")">Menu</a></li>
            </ul>
            <ul class="u-pull-right" id="nav2">
                <li><a href=""><strong>Košík</strong></a></li>
                <li><a href=""><strong>Login</strong></a></li>
            </ul>
        </div>
    </div>
    <div class="wrapper">
        @RenderBody()
    </div>
    <footer>
        <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
    </footer>
    @Scripts.Render("~/bundles/jquery")
    @*@Scripts.Render("~/bundles/bootstrap")*@
    <script src="~/Scripts/main.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>